chwd: Some cleanups
CachyOS/chwd pull request #134
Opened 2024-08-20 20:34 UTC by ventureoo

Commit 1: Removes nonfree option. In my opinion, this parameter does not make any sense anymore. For example we now have "open source Nvidia modules" as nonfree profile, so it doesn't really reflect much of the real meaning, because many drivers might be partially closed/opened. This also makes no practical sense, because if we want to install closed drivers, we just increase priority for corresponding profile which we already do. ``chwd`` displays the profile priority as the second column now.

Commit 2: Removes options related to USB. We don't handle USB profiles right now, so this just doesn't work.

Commit 3: Removes ``--is_nvidia_card``. In my opinion this is easily accomplished via lspci: ``lspci -d “10de:*:030x”`` and it also probably won't be needed anymore with https://github.com/CachyOS/chwd/pull/133.

2024-08-20 20:37 UTC, vnepogodin requested changes
run `cargo fmt --all` on the project tree

2024-08-21 14:45 UTC, vnepogodin reviewed
Looks good overall. I think we should also rename `pci_profiles` into just `profiles` in Data if we are removing pci occurs

2024-08-21 15:22 UTC, ventureoo commented
> Looks good overall. I think we should also rename `pci_profiles` into just `profiles` in Data if we are removing pci occurs

Done.

2024-08-21 16:57 UTC, vnepogodin approved these changes
legit

2024-08-21 16:57 UTC, merged